spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/product
    username: ecom
    password: ecom
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8082
